services:
  swarm:
    build:
      context: ../../
      dockerfile: src/ClrSlate.Swarm/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      McpServers__memory__command: "npx"
      McpServers__memory__args__0: "-y"
      McpServers__memory__args__1: "@modelcontextprotocol/server-memory"
      McpServers__memory__type: "stdio"
      McpServers__sequentialthinking__command: "npx"
      McpServers__sequentialthinking__args__0: "-y"
      McpServers__sequentialthinking__args__1: "@modelcontextprotocol/server-sequential-thinking"
      McpServers__sequentialthinking__type: "stdio"
    entrypoint: ["/bin/sh", "-c", "dotnet ClrSlate.Swarm.dll"]
