name: Check License Headers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-headers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check for license headers
      uses: apache/skywalking-eyes@v0.4.0
      with:
        # The mode of the action, default is `check`
        # `check` - check the license headers
        # `fix` - fix the license headers
        mode: check
        # The config file path, default is `.licenserc.yaml`
        config: .licenserc.yaml
